### ISSUE TITLE
Tables.json not found?

### ISSUE THREAD

**Issue by premshanker-ai** [BorealisAI/DT-Fixup#5]
Love this project however when I try to run it, I get this error

PS: Running this in colab pro
---

2022-10-10 19:45:42.737414: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
DEBUG:semparser.common.registry:instantiating rat_new_sl of preprocessor
DEBUG:semparser.common.registry:instantiating spider of transition_system
DEBUG:semparser.common.registry:instantiating asdl of grammar
Creating schema with meta...
ERROR:root:['  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main\n    "__main__", mod_spec)\n', '  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code\n    exec(code, run_globals)\n', '  File "/content/DT-Fixup/spider/semparser/run.py", line 122, in <module>\n    logger.error(traceback.format_stack())\n']
10/10/2022 07:45:45 ['  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main\n    "__main__", mod_spec)\n', '  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code\n    exec(code, run_globals)\n', '  File "/content/DT-Fixup/spider/semparser/run.py", line 122, in <module>\n    logger.error(traceback.format_stack())\n']
ERROR:root:Traceback (most recent call last):
  File "/content/DT-Fixup/spider/semparser/run.py", line 103, in <module>
    argument_resolver.resolve_argument(config['PREPROCESSOR'])
  File "/content/DT-Fixup/spider/semparser/common/argument_resolver.py", line 36, in resolve_argument
    return resolve_argument(argument_dict, caller)
  File "/content/DT-Fixup/spider/semparser/common/argument_resolver.py", line 56, in resolve_argument
    return caller(**resolved_arguments)
  File "/content/DT-Fixup/spider/semparser/modules/semantic_parser/preprocessor/rat_new_sl.py", line 188, in prepare_data
    schema_with_db_meta = update_schemas_with_meta(raw_schema, database_folder)
  File "/content/DT-Fixup/spider/semparser/modules/alanschema/scripts/generate_schema_with_db_meta.py", line 111, in update_schemas_with_meta
    with open(table_fpath, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'spider/tables.json'

10/10/2022 07:45:45 Traceback (most recent call last):
  File "/content/DT-Fixup/spider/semparser/run.py", line 103, in <module>
    argument_resolver.resolve_argument(config['PREPROCESSOR'])
  File "/content/DT-Fixup/spider/semparser/common/argument_resolver.py", line 36, in resolve_argument
    return resolve_argument(argument_dict, caller)
  File "/content/DT-Fixup/spider/semparser/common/argument_resolver.py", line 56, in resolve_argument
    return caller(**resolved_arguments)
  File "/content/DT-Fixup/spider/semparser/modules/semantic_parser/preprocessor/rat_new_sl.py", line 188, in prepare_data
    schema_with_db_meta = update_schemas_with_meta(raw_schema, database_folder)
  File "/content/DT-Fixup/spider/semparser/modules/alanschema/scripts/generate_schema_with_db_meta.py", line 111, in update_schemas_with_meta
    with open(table_fpath, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'spider/tables.json'

Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/content/DT-Fixup/spider/semparser/run.py", line 124, in <module>
    raise ex
  File "/content/DT-Fixup/spider/semparser/run.py", line 103, in <module>
    argument_resolver.resolve_argument(config['PREPROCESSOR'])
  File "/content/DT-Fixup/spider/semparser/common/argument_resolver.py", line 36, in resolve_argument
    return resolve_argument(argument_dict, caller)
  File "/content/DT-Fixup/spider/semparser/common/argument_resolver.py", line 56, in resolve_argument
    return caller(**resolved_arguments)
  File "/content/DT-Fixup/spider/semparser/modules/semantic_parser/preprocessor/rat_new_sl.py", line 188, in prepare_data
    schema_with_db_meta = update_schemas_with_meta(raw_schema, database_folder)
  File "/content/DT-Fixup/spider/semparser/modules/alanschema/scripts/generate_schema_with_db_meta.py", line 111, in update_schemas_with_meta
    with open(table_fpath, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'spider/tables.json'

**Comment by billy-inn** [comment]
Have you run `python prepare_data.py`?

**Comment by premshanker-ai** [comment]
Thanks a lott for the prompt reply! I actually ran it however the spider data was not downloaded as there is a zip error. I have manually loaded and unzipped the data so now it's good!
